[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

opacity = 1.0
blur = false

option_as_alt = "Both"

[font]
size = 16
normal = { family = "Hack Nerd Font Mono", style = "Regular" }

italic = { family = "Hack Nerd Font Mono", style = "Italic" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
